---
title: "EFL-4 Graphs"
author: "Nick Simone"
date: "Last Modified: `r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{EFL-4 Graphs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

------
Abstract:
   The code below plots the nine EFL-4 graphs tested by the code in the vignette "EFL-4 Test."  These graphs are stored as variables in the data of the savi package.  The variable names are given in the comments.
------

```{r, message=FALSE, eval=FALSE}
library(savi)

##################################################
#EFL4_GRAPH_1
##################################################
adjm<-matrix(c(0,1,1,1,0,0,0,0,0,0,0,0,0,
               1,0,1,1,0,0,0,0,0,0,0,0,0,
               1,1,0,1,0,0,0,0,0,0,0,0,0,
               1,1,1,0,1,1,1,0,0,0,0,0,0,
               0,0,0,1,0,1,1,0,0,0,0,0,0,
               0,0,0,1,1,0,1,0,0,0,0,0,0,
               0,0,0,1,1,1,0,1,1,1,0,0,0,
               0,0,0,0,0,0,1,0,1,1,0,0,0,
               0,0,0,0,0,0,1,1,0,1,0,0,0,
               0,0,0,0,0,0,1,1,1,0,1,1,1,
               0,0,0,0,0,0,0,0,0,1,0,1,1,
               0,0,0,0,0,0,0,0,0,1,1,0,1,
               0,0,0,0,0,0,0,0,0,1,1,1,0),
             nrow=13,
             ncol=13,
             byrow = TRUE)
g=graph_from_adjacency_matrix(adjm, mode=c("undirected"))

V(g)$group=c(1,1,1,1,1,1,1,1,1,1,1,1,1)
V(g)$name=c(" "," "," "," "," "," "," "," "," "," "," "," "," ")

plotWithGroups(g,1)


##################################################
#EFL4_GRAPH_2
##################################################
adjm<-matrix(c(0,1,1,1,0,0,0,0,0,1,1,1,
               1,0,1,1,0,0,0,0,0,0,0,0,
               1,1,0,1,0,0,0,0,0,0,0,0,
               1,1,1,0,1,1,1,0,0,0,0,0,
               0,0,0,1,0,1,1,0,0,0,0,0,
               0,0,0,1,1,0,1,0,0,0,0,0,
               0,0,0,1,1,1,0,1,1,1,0,0,
               0,0,0,0,0,0,1,0,1,1,0,0,
               0,0,0,0,0,0,1,1,0,1,0,0,
               1,0,0,0,0,0,1,1,1,0,1,1,
               1,0,0,0,0,0,0,0,0,1,0,1,
               1,0,0,0,0,0,0,0,0,1,1,0),
             nrow=12,
             ncol=12,
             byrow = TRUE)
g=graph_from_adjacency_matrix(adjm, mode=c("undirected"))

V(g)$group=c(1,1,1,1,1,1,1,1,1,1,1,1)
V(g)$name=c(" "," "," "," "," "," "," "," "," "," "," "," ")

plotWithGroups(g,1)

##################################################
#EFL4_GRAPH_3
##################################################
adjm<-matrix(c(0,1,1,1,0,0,0,0,0,0,0,0,
               1,0,1,1,0,0,0,0,0,0,0,0,
               1,1,0,1,0,1,0,1,1,0,0,0,
               1,1,1,0,1,1,1,0,0,0,0,0,
               0,0,0,1,0,1,1,0,0,0,0,0,
               0,0,1,1,1,0,1,1,1,0,0,0,
               0,0,0,1,1,1,0,0,0,1,1,1,
               0,0,1,0,0,1,0,0,1,0,0,0,
               0,0,1,0,0,1,0,1,0,0,0,0,
               0,0,0,0,0,0,1,0,0,0,1,1,
               0,0,0,0,0,0,1,0,0,1,0,1,
               0,0,0,0,0,0,1,0,0,1,1,0),
             nrow=12,
             ncol=12,
             byrow = TRUE)
g=graph_from_adjacency_matrix(adjm, mode=c("undirected"))

V(g)$group=c(1,1,1,1,1,1,1,1,1,1,1,1)
V(g)$name=c(" "," "," "," "," "," "," "," "," "," "," "," ")

plotWithGroups(g,1)


##################################################
#EFL4_GRAPH_4
##################################################
adjm<-matrix(c(0,1,1,1,0,1,0,0,0,1,1,
               1,0,1,1,0,0,0,0,0,0,0,
               1,1,0,1,0,0,1,1,1,0,0,
               1,1,1,0,1,1,1,0,0,0,0,
               0,0,0,1,0,1,1,0,0,0,0,
               1,0,0,1,1,0,1,0,0,1,1,
               0,0,1,1,1,1,0,1,1,0,0,
               0,0,1,0,0,0,1,0,1,0,0,
               0,0,1,0,0,0,1,1,0,0,0,
               1,0,0,0,0,1,0,0,0,0,1,
               1,0,0,0,0,1,0,0,0,1,0),
             nrow=11,
             ncol=11,
             byrow = TRUE)
g=graph_from_adjacency_matrix(adjm, mode=c("undirected"))

V(g)$group=c(1,1,1,1,1,1,1,1,1,1,1)
V(g)$name=c(" "," "," "," "," "," "," "," "," "," "," ")

plotWithGroups(g,1)


##################################################
#EFL4_GRAPH_5
##################################################
adjm<-matrix(c(0,1,1,1,0,0,0,0,0,0,
               1,0,1,1,1,1,1,0,0,0,
               1,1,0,1,0,1,0,0,1,1,
               1,1,1,0,0,0,1,1,1,0,
               0,1,0,0,0,1,1,0,0,0,
               0,1,1,0,1,0,1,0,1,1,
               0,1,0,1,1,1,0,1,1,0,
               0,0,0,1,0,0,1,0,1,0,
               0,0,1,1,0,1,1,1,0,1,
               0,0,1,0,0,1,0,0,1,0),
             nrow=10,
             ncol=10,
             byrow = TRUE)
g=graph_from_adjacency_matrix(adjm, mode=c("undirected"))

V(g)$group=c(1,1,1,1,1,1,1,1,1,1)
V(g)$name=c(" "," "," "," "," "," "," "," "," "," ")

plotWithGroups(g,1)


##################################################
#EFL4_GRAPH_6
##################################################
adjm<-matrix(c(0,1,1,1,1,1,1,1,1,1,0,0,0,
               1,0,1,1,0,0,0,0,0,0,0,0,0,
               1,1,0,1,0,0,0,0,0,0,0,0,0,
               1,1,1,0,0,0,0,0,0,0,0,0,0,
               1,0,0,0,0,1,1,0,0,0,0,0,0,
               1,0,0,0,1,0,1,0,0,0,0,0,0,
               1,0,0,0,1,1,0,0,0,0,0,0,0,
               1,0,0,0,0,0,0,0,1,1,0,0,0,
               1,0,0,0,0,0,0,1,0,1,0,0,0,
               1,0,0,0,0,0,0,1,1,0,1,1,1,
               0,0,0,0,0,0,0,0,0,1,0,1,1,
               0,0,0,0,0,0,0,0,0,1,1,0,1,
               0,0,0,0,0,0,0,0,0,1,1,1,0),
             nrow=13,
             ncol=13,
             byrow = TRUE)
g=graph_from_adjacency_matrix(adjm, mode=c("undirected"))

V(g)$group=c(1,1,1,1,1,1,1,1,1,1,1,1,1)
V(g)$name=c(" "," "," "," "," "," "," "," "," "," "," "," "," ")

plotWithGroups(g,1)

##################################################
#EFL4_GRAPH_7
##################################################
adjm<-matrix(c(0,1,1,1,1,1,1,1,1,1,0,0,
               1,0,1,1,0,0,0,0,0,0,0,0,
               1,1,0,1,0,0,0,0,0,0,0,0,
               1,1,1,0,0,0,0,0,0,1,1,1,
               1,0,0,0,0,1,1,0,0,0,0,0,
               1,0,0,0,1,0,1,0,0,0,0,0,
               1,0,0,0,1,1,0,0,0,0,0,0,
               1,0,0,0,0,0,0,0,1,1,0,0,
               1,0,0,0,0,0,0,1,0,1,0,0,
               1,0,0,1,0,0,0,1,1,0,1,1,
               0,0,0,1,0,0,0,0,0,1,0,1,
               0,0,0,1,0,0,0,0,0,1,1,0),
             nrow=12,
             ncol=12,
             byrow = TRUE)
g=graph_from_adjacency_matrix(adjm, mode=c("undirected"))

V(g)$group=c(1,1,1,1,1,1,1,1,1,1,1,1)
V(g)$name=c(" "," "," "," "," "," "," "," "," "," "," "," ")

plotWithGroups(g,1)

##################################################
#EFL4_GRAPH_8
##################################################
adjm<-matrix(c(0,1,1,1,1,1,1,1,1,1,0,
               1,0,1,1,0,0,0,0,0,0,0,
               1,1,0,1,0,0,0,0,0,0,0,
               1,1,1,0,0,0,1,0,0,1,1,
               1,0,0,0,0,1,1,0,0,0,0,
               1,0,0,0,1,0,1,0,0,0,0,
               1,0,0,1,1,1,0,0,0,1,1,
               1,0,0,0,0,0,0,0,1,1,0,
               1,0,0,0,0,0,0,1,0,1,0,
               1,0,0,1,0,0,1,1,1,0,1,
               0,0,0,1,0,0,1,0,0,1,0),
             nrow=11,
             ncol=11,
             byrow = TRUE)
g=graph_from_adjacency_matrix(adjm, mode=c("undirected"))

V(g)$group=c(1,1,1,1,1,1,1,1,1,1,1)
V(g)$name=c("1","2","3","4","5","6","7","8","9","10","11")

plotWithGroups(g,1)


##################################################
#EFL4_GRAPH_9
##################################################
adjm<-matrix(c(0,1,1,1,1,1,1,1,1,1,1,1,1,
               1,0,1,1,0,0,0,0,0,0,0,0,0,
               1,1,0,1,0,0,0,0,0,0,0,0,0,
               1,1,1,0,0,0,0,0,0,0,0,0,0,
               1,0,0,0,0,1,1,0,0,0,0,0,0,
               1,0,0,0,1,0,1,0,0,0,0,0,0,
               1,0,0,0,1,1,0,0,0,0,0,0,0,
               1,0,0,0,0,0,0,0,1,1,0,0,0,
               1,0,0,0,0,0,0,1,0,1,0,0,0,
               1,0,0,0,0,0,0,1,1,0,0,0,0,
               1,0,0,0,0,0,0,0,0,0,0,1,1,
               1,0,0,0,0,0,0,0,0,0,1,0,1,
               1,0,0,0,0,0,0,0,0,0,1,1,0),
             nrow=13,
             ncol=13,
             byrow = TRUE)
g=graph_from_adjacency_matrix(adjm, mode=c("undirected"))

V(g)$group=c(1,1,1,1,1,1,1,1,1,1,1,1,1)
V(g)$name=c(" "," "," "," "," "," "," "," "," "," "," "," "," ")

plotWithGroups(g,1)

```
