---
title: "EFL-4 Test"
author: "Nick Simone"
date: "Last Modified: `r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{EFL-4 Test}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

------
Abstract:
   The following code checks 9 different EFL-4 graphs for strict local minimum states. Each graph was checked 20 times by starting at 20 random initial states and seeing if the greedy algorithm reached a score of 0.  If it did not, then it is possible the algorithm got stuck in a strict local minimum state.  However, it is also possible that the algorithm needed to run longer to find a lower score.  
   
   In this case, a score of 0 was reached every time.  This is evidence that no strict local minimum states exist in an EFL-4 graph.  For a more indepth analysis, see the associated thesis.
------

```{r, message=FALSE, eval=FALSE}
library(savi)

#set seed
set.seed(142)

#Set the Scoring Function
myScoreFunction<-function(g){
  #Get the number of Groups
  numOfGroups<-max(V(g)$group)

  #Count the number of inter-group edges
  s<-0
  for(i in c(1:numOfGroups)){
    s<-s+length(which(tail_of(g,E(g))$group==i & head_of(g,E(g))$group==i))
  }

  return(s)
}

#Create a list of 9 EFL-4 graphs
g<-list(EFL4_GRAPH_1,EFL4_GRAPH_2,EFL4_GRAPH_3,EFL4_GRAPH_4,EFL4_GRAPH_5,EFL4_GRAPH_6,EFL4_GRAPH_7,EFL4_GRAPH_8,EFL4_GRAPH_9)
arr<-c()
flag<-0

#Loop through the graphs
for(n in 1:9){
  myGraph<-g[[n]]

  #Try 20 times to find a local minimum state
  for(i in 1:20){
    myGraph<-addRandomGroups(myGraph,4)
    results_Greedy<-runSavi(myGraph,4,"Greedy",1000,myScoreFunction)
    if(results_Greedy$minScore!=0){
      print("Found possible local minimum state")
      arr<-results_Greedy
      flag=1
      break
    }

    #Print out progress
    print(paste("EFL4 -",n,"iter - ",i))
  }
  if(flag==1){
    break
  }
}

if(flag==0){
  print("No local minimum state found")
}

```
